version: "3.8"
services:
  rollee:
    environment:
      - PYTHONUNBUFFERED=1
    build: .
    command: sh -c "python /rollee/manage.py makemigrations && python /rollee/manage.py migrate && python /rollee/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/rollee
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:12.12-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - 5432:5432
