# Generated by Django 4.2.3 on 2023-07-27 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('status', models.CharField()),
                ('avatar', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField()),
                ('last_update', models.DateTimeField()),
                ('currency', models.CharField()),
                ('gross_earnings', models.FloatField()),
                ('net_amount', models.FloatField()),
                ('taxes', models.FloatField()),
                ('bonus_amount', models.FloatField()),
                ('platform_fee', models.FloatField()),
                ('activity', models.JSONField(null=True)),
                ('trips', models.JSONField(null=True)),
                ('employment', models.JSONField(null=True)),
                ('documents', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('logo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField()),
                ('model', models.CharField()),
                ('year', models.CharField()),
                ('license_plate', models.CharField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='rollee.accountrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('full_name', models.CharField()),
                ('phone', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('image_url', models.URLField()),
                ('street', models.CharField()),
                ('zip', models.CharField()),
                ('country_phone_code', models.CharField()),
                ('licence_number', models.CharField(null=True)),
                ('licence_expire_dt', models.DateField(null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='rollee.accountrecord')),
            ],
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='platform',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rollee.platform'),
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='rollee.user'),
        ),
    ]
